// File generated by FlutterFire CLI.
// This file is a placeholder and should be replaced with the actual file
// generated by running 'flutterfire configure' in the project directory.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // This is a placeholder implementation
    // In a real app, this would be generated by the FlutterFire CLI
    return const FirebaseOptions(
      apiKey: 'YOUR-API-KEY',
      appId: 'YOUR-APP-ID',
      messagingSenderId: 'YOUR-SENDER-ID',
      projectId: 'YOUR-PROJECT-ID',
    );
  }
}