class AppConstants {
  // App Information
  static const String appName = 'Safe Travels';
  static const String appVersion = '1.0.0';
  
  // Location
  static const String defaultLocation = 'Philadelphia, PA';
  
  // Transportation Types
  static const String regionalRail = 'Regional Rail';
  static const String bus = 'Bus';
  static const String subway = 'Subway';
  static const String trolley = 'Trolley';
  
  // Starting Locations
  static const List<String> startingLocations = [
    "30th Street Station",
    "49th Street",
    "Airport Terminal A",
    "Airport Terminal B",
    "Airport Terminal C-D",
    "Airport Terminal E-F",
    "Allegheny",
    "Ambler",
    "Angora",
    "Ardmore",
    "Ardsley",
    "Bala",
    "Berwyn",
    "Bethayres",
    "Bridesburg",
    "Bristol",
    "Bryn Mawr",
    "Chalfont",
    "Chester",
    "Chestnut Hill East",
    "Churchmans Crossing",
    "Claymont",
    "Clifton-Aldan",
    "Colmar",
    "Conshohocken",
    "Cornwells Heights",
    "Crestmont",
    "Croydon",
    "Crum Lynne",
    "Curtis Park",
    "Cynwyd",
    "Darby",
    "Daylesford",
    "Delaware Valley University",
    "Devon",
    "Downingtown",
    "Doylestown",
    "East Falls",
    "Eddington",
    "Eddystone",
    "Elkins Park",
    "Elm Street",
    "Elwyn",
    "Exton",
    "Fernwood-Yeadon",
    "Fern Rock",
    "Folcroft",
    "Forest Hills",
    "Fort Washington",
    "Fortuna",
    "Fox Chase",
    "Germantown",
    "Gladstone",
    "Glenolden",
    "Glenside",
    "Gravers",
    "Gwynedd Valley",
    "Hatboro",
    "Haverford",
    "Highland Avenue",
    "Holmesburg Junction",
    "Ivy Ridge",
    "Jefferson Station",
    "Jenkintown-Wyncote",
    "Langhorne",
    "Lansdale",
    "Lansdowne",
    "Levittown",
    "Link Belt",
    "Main Street",
    "Malvern",
    "Manayunk",
    "Marcus Hook",
    "Meadowbrook",
    "Media",
    "Melrose Park",
    "Miquon",
    "Morton",
    "Mount Airy",
    "Moylan-Rose Valley",
    "Neshaminy Falls",
    "New Britain",
    "Newark",
    "Noble",
    "North Broad",
    "North Philadelphia",
    "North Wales",
    "Norristown Transportation Center",
    "Norristown Elm Street",
    "Norwood",
    "Paoli",
    "Penllyn",
    "Pennbrook",
    "Philmont",
    "Primos",
    "Prospect Park",
    "Radnor",
    "Ridley Park",
    "Rosemont",
    "Roslyn",
    "Rydal",
    "Ryers",
    "St. Davids",
    "Secane",
    "Sedgwick",
    "Sharon Hill",
    "Somerton",
    "Spring Mill",
    "Stenton",
    "Strafford",
    "Suburban Station",
    "Swarthmore",
    "Tacony",
    "Temple University",
    "Thorndale",
    "Torresdale",
    "Trenton",
    "Trevose",
    "University City",
    "Villanova",
    "Wallingford",
    "Warminster",
    "Washington Lane",
    "Wawa",
    "Wayne",
    "Wayne Junction",
    "West Trenton",
    "Whitford",
    "Willow Grove",
    "Wilmington",
    "Wissahickon",
    "Wister",
    "Woodbourne",
    "Wyndmoor",
    "Wynnefield Avenue",
    "Yardley"
  ];
  
  // Ending Locations
  static const List<String> endingLocations = [
    "30th Street Station",
    "49th Street",
    "Airport Terminal A",
    "Airport Terminal B",
    "Airport Terminal C-D",
    "Airport Terminal E-F",
    "Allegheny",
    "Ambler",
    "Angora",
    "Ardmore",
    "Ardsley",
    "Bala",
    "Berwyn",
    "Bethayres",
    "Bridesburg",
    "Bristol",
    "Bryn Mawr",
    "Chalfont",
    "Chester",
    "Chestnut Hill East",
    "Churchmans Crossing",
    "Claymont",
    "Clifton-Aldan",
    "Colmar",
    "Conshohocken",
    "Cornwells Heights",
    "Crestmont",
    "Croydon",
    "Crum Lynne",
    "Curtis Park",
    "Cynwyd",
    "Darby",
    "Daylesford",
    "Delaware Valley University",
    "Devon",
    "Downingtown",
    "Doylestown",
    "East Falls",
    "Eddington",
    "Eddystone",
    "Elkins Park",
    "Elm Street",
    "Elwyn",
    "Exton",
    "Fernwood-Yeadon",
    "Fern Rock",
    "Folcroft",
    "Forest Hills",
    "Fort Washington",
    "Fortuna",
    "Fox Chase",
    "Germantown",
    "Gladstone",
    "Glenolden",
    "Glenside",
    "Gravers",
    "Gwynedd Valley",
    "Hatboro",
    "Haverford",
    "Highland Avenue",
    "Holmesburg Junction",
    "Ivy Ridge",
    "Jefferson Station",
    "Jenkintown-Wyncote",
    "Langhorne",
    "Lansdale",
    "Lansdowne",
    "Levittown",
    "Link Belt",
    "Main Street",
    "Malvern",
    "Manayunk",
    "Marcus Hook",
    "Meadowbrook",
    "Media",
    "Melrose Park",
    "Miquon",
    "Morton",
    "Mount Airy",
    "Moylan-Rose Valley",
    "Neshaminy Falls",
    "New Britain",
    "Newark",
    "Noble",
    "North Broad",
    "North Philadelphia",
    "North Wales",
    "Norristown Transportation Center",
    "Norristown Elm Street",
    "Norwood",
    "Paoli",
    "Penllyn",
    "Pennbrook",
    "Philmont",
    "Primos",
    "Prospect Park",
    "Radnor",
    "Ridley Park",
    "Rosemont",
    "Roslyn",
    "Rydal",
    "Ryers",
    "St. Davids",
    "Secane",
    "Sedgwick",
    "Sharon Hill",
    "Somerton",
    "Spring Mill",
    "Stenton",
    "Strafford",
    "Suburban Station",
    "Swarthmore",
    "Tacony",
    "Temple University",
    "Thorndale",
    "Torresdale",
    "Trenton",
    "Trevose",
    "University City",
    "Villanova",
    "Wallingford",
    "Warminster",
    "Washington Lane",
    "Wawa",
    "Wayne",
    "Wayne Junction",
    "West Trenton",
    "Whitford",
    "Willow Grove",
    "Wilmington",
    "Wissahickon",
    "Wister",
    "Woodbourne",
    "Wyndmoor",
    "Wynnefield Avenue",
    "Yardley"
  ];
  
  // Age Groups
  static const String minor = 'Minor';
  static const String adult = 'Adult';
  
  // Rating Categories
  static const String punctuality = 'Punctuality';
  static const String safety = 'Safety';
  static const String cleanliness = 'Cleanliness';
  static const String overall = 'Overall';
  
  // Navigation
  static const String home = 'HOME';
  static const String profile = 'PROFILE';
  
  // Screen Titles
  static const String transportationTitle = 'TRANSPORTATION:';
  static const String filterAgeTitle = 'Filter Age:';
  static const String reviewTitle = 'Review';
  static const String addReviewTitle = 'Add Review';
  static const String editReviewTitle = 'Edit Review';
  
  // Button Labels
  static const String showReviews = 'Show Reviews';
  static const String publish = 'PUBLISH';
  static const String select = 'Select';
  
  // Placeholders
  static const String reviewPlaceholder = 'Type a review...';
  static const String usernamePlaceholder = 'Username';
  
  // Error Messages
  static const String locationError = 'Please select both starting and ending locations';
  static const String networkError = 'Network error. Please try again.';
  static const String authError = 'Authentication error. Please try again.';
  static const String reviewError = 'Error submitting review. Please try again.';
}
